// <auto-generated />
namespace eTimeTrack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UnassignedEmployeeProjects1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UnassignedEmployeeProjects1));
        
        string IMigrationMetadata.Id
        {
            get { return "202408211736583_UnassignedEmployeeProjects1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
